[mypy]
python_version = 3.12
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
no_implicit_optional = True
strict_optional = True

# Ignore missing type hints in third party libraries
[mypy.plugins.numpy.*]
follow_imports = silent

[mypy-pytest.*]
ignore_missing_imports = True

[mypy-flask_sqlalchemy.*]
ignore_missing_imports = True

[mypy-GitPython.*]
ignore_missing_imports = True

[mypy-sphinx.*]
ignore_missing_imports = True

[mypy-sphinxcontrib.*]
ignore_missing_imports = True

[mypy-sphinxcontrib_napoleon.*]
ignore_missing_imports = True

[mypy.plugins.setuptools.extension]
enabled = True

[mypy.plugins.setuptools]
enabled = True

[mypy.plugins.setuptools_scm]
enabled = True

[mypy-setuptools.*]
ignore_missing_imports = True

[mypy-black.*]
ignore_missing_imports = True

[mypy-dotenv.*]
ignore_missing_imports = True

[mypy-python_dotenv.*]
ignore_missing_imports = True

[mypy-flask.*]
ignore_missing_imports = True

[mypy-requests.*]
ignore_missing_imports = True

# Handle src.* imports
# [mypy-src.*]
# ignore_missing_imports = True
# follow_imports = normal

# For modules that we can't install type stubs for
[mypy-pylint.*]
ignore_missing_imports = True
